
set -g mouse on
set -s escape-time 0
set-option -g prefix C-s

set -g status-interval 1
set -g status-justify centre
set -g status-left-length 20
set -g status-right-length 140

set -g base-index 1

set -g history-limit 5000 

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r source-file ~/.config/tmux.conf \; display-message "Config reloaded..."

# clear both screen and history
bind -n C-l send-keys C-l \; run 'sleep 0.2' \; clear-history

set -g default-terminal "screen-256color"
