#!/usr/bin/env bash
# ghostty theme adapter

_ghostty_realpath() {
  python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"
}

_ghostty_set_theme_line() {
  local cfg="$1" id="$2"
  local real tmp dir
  real="$(_ghostty_realpath "$cfg")"
  dir="$(dirname "$real")"
  tmp="$(mktemp "$dir/.theme.XXXXXX")"

  if grep -qE '^[[:space:]]*theme[[:space:]]*=' "$real"; then
    sed -E "s|^[[:space:]]*theme[[:space:]]*=.*|theme = ${id}|" "$real" >"$tmp"
  else
    cat "$real" >"$tmp"
    printf '\ntheme = %s\n' "$id" >>"$tmp"
  fi
  # Move onto the real file so a symlink at $cfg is preserved.
  mv "$tmp" "$real"
  theme_log "set theme = $id in $real"
}

apply() {
  local id="$1"
  local dest_dir="$HOME/.config/ghostty/themes"
  # Ghostty theme names map 1:1 to filenames (no extension).
  local dest="$dest_dir/${id}"
  local override cfg found
  local -a cfg_candidates seen_reals
  local real

  mkdir -p "$dest_dir"

  # Remove legacy .conf copies from earlier switcher versions
  rm -f "${dest}.conf"

  if override="$(theme_override "$id" ghostty conf)"; then
    cp "$override" "$dest"
  else
    theme_load_palette "$id"
    cat >"$dest" <<EOF
# Generated by theme switcher from palette $id
background = ${THEME_bg}
foreground = ${THEME_fg}
cursor-color = ${THEME_cursor}
cursor-text = ${THEME_cursor_text}
selection-background = ${THEME_selection_bg}
selection-foreground = ${THEME_selection_fg}
palette = 0=${THEME_color0}
palette = 1=${THEME_color1}
palette = 2=${THEME_color2}
palette = 3=${THEME_color3}
palette = 4=${THEME_color4}
palette = 5=${THEME_color5}
palette = 6=${THEME_color6}
palette = 7=${THEME_color7}
palette = 8=${THEME_color8}
palette = 9=${THEME_color9}
palette = 10=${THEME_color10}
palette = 11=${THEME_color11}
palette = 12=${THEME_color12}
palette = 13=${THEME_color13}
palette = 14=${THEME_color14}
palette = 15=${THEME_color15}
EOF
  fi
  theme_log "wrote $dest"

  cfg_candidates=(
    "$HOME/.config/ghostty/config"
    "$HOME/Library/Application Support/com.mitchellh.ghostty/config"
  )
  found=0
  seen_reals=()
  for cfg in "${cfg_candidates[@]}"; do
    [[ -e "$cfg" || -L "$cfg" ]] || continue
    [[ -f "$cfg" || -L "$cfg" ]] || continue
    real="$(_ghostty_realpath "$cfg")"
    [[ -f "$real" ]] || continue
    # Skip duplicates (symlink + target)
    local already=0 s
    for s in "${seen_reals[@]:-}"; do
      [[ "$s" == "$real" ]] && already=1 && break
    done
    [[ "$already" -eq 1 ]] && continue
    seen_reals+=("$real")
    _ghostty_set_theme_line "$cfg" "$id"
    found=1
  done

  if [[ "$found" -eq 0 ]]; then
    theme_warn "ghostty config not found; theme file installed only"
  fi

  # Ghostty 1.2+ reloads config on SIGUSR2 (same as cmd+shift+,).
  local pids
  pids="$(pgrep -x ghostty 2>/dev/null || true)"
  if [[ -z "$pids" ]]; then
    pids="$(pgrep -f '/Ghostty\.app/Contents/MacOS/ghostty' 2>/dev/null || true)"
  fi
  if [[ -n "$pids" ]]; then
    # shellcheck disable=SC2086
    if kill -USR2 $pids 2>/dev/null; then
      theme_log "sent SIGUSR2 to Ghostty (config reload)"
    else
      theme_warn "could not signal Ghostty; press cmd+shift+, to reload"
    fi
  else
    theme_log "Ghostty not running; theme will apply on next launch"
  fi
}
