set -g status-bg "#AAAAAA"
set -g status-fg "#000000"
set -g status-left-style "bg=#0055AA,fg=#FFFFFF"
set -g status-right-style "bg=#0055AA,fg=#FFFFFF"
set -g window-status-current-style "bg=#FFFFFF,fg=#000000"
set -g window-status-style "bg=#AAAAAA,fg=#555555"
set -g pane-border-style "fg=#555555"
set -g pane-active-border-style "fg=#0055AA"
set -g mode-style "bg=#0055AA,fg=#FFFFFF"
