set -g status-bg "#1a1b26"
set -g status-fg "#c0caf5"
set -g status-left-style "bg=#7aa2f7,fg=#1a1b26"
set -g status-right-style "bg=#7aa2f7,fg=#1a1b26"
set -g window-status-current-style "bg=#7dcfff,fg=#1a1b26"
set -g window-status-style "bg=#1a1b26,fg=#565f89"
set -g pane-border-style "fg=#414868"
set -g pane-active-border-style "fg=#7aa2f7"
set -g mode-style "bg=#7aa2f7,fg=#1a1b26"
