-- Generated by theme switcher (amiga)
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "amiga"
vim.o.background = "light"

local bg = "#AAAAAA"
local fg = "#000000"
local accent = "#0055AA"
local dim = "#8B4500"
local bright = "#228822"
local surface = "#999999"
local comment = "#555555"
local sel_bg = "#0055AA"
local sel_fg = "#FFFFFF"

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hi("Normal", { fg = fg, bg = "NONE" })
hi("NormalFloat", { fg = fg, bg = surface })
hi("NormalNC", { fg = fg, bg = "NONE" })
hi("Directory", { fg = accent, bold = true })
hi("NonText", { fg = comment })
hi("Conceal", { fg = comment })
hi("Comment", { fg = comment, italic = true })
hi("Constant", { fg = bright })
hi("String", { fg = dim })
hi("Identifier", { fg = fg })
hi("Function", { fg = accent })
hi("Statement", { fg = bright })
hi("PreProc", { fg = dim })
hi("Type", { fg = accent })
hi("Special", { fg = bright })
hi("Underlined", { fg = accent, underline = true })
hi("Todo", { fg = sel_fg, bg = accent, bold = true })
hi("LineNr", { fg = comment })
hi("Folded", { fg = fg, bg = surface })
hi("FoldColumn", { fg = comment, bg = "NONE" })
-- Workbench-style selection: white on blue (or theme selection colors)
hi("CursorLine", { bg = "NONE", fg = sel_fg })
hi("CursorLineNr", { fg = sel_fg, bg = sel_bg, bold = true })
hi("Visual", { bg = sel_bg, fg = sel_fg })
hi("Search", { bg = dim, fg = bg })
hi("IncSearch", { bg = accent, fg = sel_fg })
-- StatusLine feeds lualine auto-theme section C — keep it dark + bright text
hi("StatusLine", { fg = fg, bg = bg, bold = true })
hi("StatusLineNC", { fg = dim, bg = surface })
hi("VertSplit", { fg = comment })
hi("WinSeparator", { fg = comment })
hi("Pmenu", { fg = fg, bg = surface })
-- PmenuSel.bg is lualine auto "normal" accent (mode pill)
hi("PmenuSel", { fg = sel_fg, bg = accent, bold = true })
hi("TelescopeSelection", { fg = sel_fg, bg = sel_bg, bold = true })
hi("TelescopeSelectionCaret", { fg = sel_fg, bg = sel_bg })
-- Snacks explorer / picker: default file names must use Normal fg (not NonText grey)
hi("SnacksPickerFile", { fg = fg })
hi("SnacksPickerDirectory", { fg = accent, bold = true })
hi("SnacksPickerDir", { fg = comment })
hi("SnacksPickerPathHidden", { fg = comment })
hi("SnacksPickerPathIgnored", { fg = comment })
hi("SnacksPickerDimmed", { fg = comment })
hi("SnacksPickerComment", { fg = comment })
hi("SnacksPickerTotals", { fg = comment })
hi("SnacksPickerTree", { fg = comment })
hi("SnacksPickerGitStatusUntracked", { fg = comment })
hi("SnacksPickerGitStatusIgnored", { fg = comment })
hi("SnacksPickerGitStatusAdded", { fg = bright })
hi("SnacksPickerGitStatusModified", { fg = dim })
hi("SnacksPickerGitStatusDeleted", { fg = "#AA0000" })
-- Neo-tree fallbacks
hi("NeoTreeNormal", { fg = fg, bg = "NONE" })
hi("NeoTreeNormalNC", { fg = fg, bg = "NONE" })
hi("NeoTreeFileName", { fg = fg })
hi("NeoTreeDirectoryName", { fg = accent, bold = true })
hi("NeoTreeDimText", { fg = comment })
-- Bufferline / tabs: inactive must stay readable (don't use near-black Comment)
hi("TabLine", { fg = dim, bg = bg })
hi("TabLineFill", { fg = dim, bg = bg })
hi("TabLineSel", { fg = sel_fg, bg = sel_bg, bold = true })
hi("BufferLineFill", { fg = dim, bg = bg })
hi("BufferLineBackground", { fg = dim, bg = bg })
hi("BufferLineBuffer", { fg = dim, bg = bg })
hi("BufferLineBufferVisible", { fg = dim, bg = bg })
hi("BufferLineBufferSelected", { fg = sel_fg, bg = sel_bg, bold = true, italic = true })
hi("BufferLineTab", { fg = dim, bg = bg })
hi("BufferLineTabSelected", { fg = sel_fg, bg = sel_bg, bold = true })
hi("BufferLineTabClose", { fg = dim, bg = bg })
hi("BufferLineCloseButton", { fg = dim, bg = bg })
hi("BufferLineCloseButtonVisible", { fg = dim, bg = bg })
hi("BufferLineCloseButtonSelected", { fg = sel_fg, bg = sel_bg })
hi("BufferLineSeparator", { fg = bg, bg = bg })
hi("BufferLineSeparatorVisible", { fg = bg, bg = bg })
hi("BufferLineSeparatorSelected", { fg = sel_bg, bg = sel_bg })
hi("BufferLineIndicatorSelected", { fg = sel_fg, bg = sel_bg })
hi("BufferLineIndicatorVisible", { fg = dim, bg = bg })
hi("BufferLineModified", { fg = dim, bg = bg })
hi("BufferLineModifiedVisible", { fg = dim, bg = bg })
hi("BufferLineModifiedSelected", { fg = sel_fg, bg = sel_bg })
hi("BufferLineDuplicate", { fg = comment, bg = bg, italic = true })
hi("BufferLineDuplicateVisible", { fg = comment, bg = bg, italic = true })
hi("BufferLineDuplicateSelected", { fg = sel_fg, bg = sel_bg, italic = true })
hi("BufferLineNumbers", { fg = dim, bg = bg })
hi("BufferLineNumbersVisible", { fg = dim, bg = bg })
hi("BufferLineNumbersSelected", { fg = sel_fg, bg = sel_bg, bold = true })
hi("BufferLineErrorSelected", { fg = sel_fg, bg = sel_bg, bold = true })
hi("BufferLineErrorDiagnosticSelected", { fg = sel_fg, bg = sel_bg })
hi("BufferLineWarningSelected", { fg = sel_fg, bg = sel_bg, bold = true })
hi("BufferLineWarningDiagnosticSelected", { fg = sel_fg, bg = sel_bg })
hi("BufferLineInfoSelected", { fg = sel_fg, bg = sel_bg })
hi("BufferLineInfoDiagnosticSelected", { fg = sel_fg, bg = sel_bg })
hi("BufferLineHintSelected", { fg = sel_fg, bg = sel_bg })
hi("BufferLineHintDiagnosticSelected", { fg = sel_fg, bg = sel_bg })
hi("DiagnosticError", { fg = "#AA0000" })
hi("DiagnosticWarn", { fg = dim })
hi("DiagnosticInfo", { fg = accent })
hi("DiagnosticHint", { fg = bright })
hi("DiffAdd", { fg = bright })
hi("DiffChange", { fg = dim })
hi("DiffDelete", { fg = "#AA0000" })
hi("DiffText", { fg = accent, bold = true })

-- Force white-on-selection current line (CursorLine fg is ignored with Treesitter).
hi("AmigaCursorLine", { fg = sel_fg, bg = sel_bg })
vim.opt.cursorline = true
local ns = vim.api.nvim_create_namespace("theme_solid_cursorline")
local function paint_cursorline()
  if vim.g.colors_name ~= "amiga" then
    vim.api.nvim_buf_clear_namespace(0, ns, 0, -1)
    return
  end
  vim.api.nvim_buf_clear_namespace(0, ns, 0, -1)
  local ok, cursor = pcall(vim.api.nvim_win_get_cursor, 0)
  if not ok then
    return
  end
  local line = cursor[1] - 1
  local text = vim.api.nvim_buf_get_lines(0, line, line + 1, false)[1] or ""
  local end_col = #text
  if end_col == 0 then
    vim.api.nvim_buf_set_extmark(0, ns, line, 0, {
      line_hl_group = "AmigaCursorLine",
      hl_mode = "replace",
      priority = 4096,
    })
  else
    vim.api.nvim_buf_set_extmark(0, ns, line, 0, {
      end_row = line,
      end_col = end_col,
      hl_group = "AmigaCursorLine",
      line_hl_group = "AmigaCursorLine",
      hl_mode = "replace",
      priority = 4096,
    })
  end
end
vim.api.nvim_create_autocmd({ "ColorScheme", "CursorMoved", "CursorMovedI", "BufEnter", "InsertEnter", "InsertLeave", "TextChanged", "TextChangedI" }, {
  group = vim.api.nvim_create_augroup("ThemeSolidCursorline", { clear = true }),
  callback = paint_cursorline,
})
paint_cursorline()
